#!/bin/sh

~/dotfiles/install.py --submodules
~/dotfiles/install.py -sf vim
~/dotfiles/install.py -sf *

xrdb ~/.Xresources
eval `dircolors ~/.dircolors`
~/dotfiles/gnome-terminal-colors-solarized/set_dark.sh
export MC_SKIN=$HOME/.config/mc/solarized.ini

ln -s ~/.local/share/themes ~/.themes
ln -s ~/.config/sublime-text-3 ~/.sublime-text-3
